import type { ListingFormInputs } from "../types/property";

export const defaultResidentialValues: ListingFormInputs = {
    propertyPurpose: 0,
    title: "",
    agentId: "",
    propertyStatus: 0,
    propertyType: 0,
    compoundId: "",
    address: "",
    city: "",
    googleMapsUrl: "",
    price: 0,
    square: 0,
    description: "",
    amenities: {
        hasElectricityLine: false,
        hasWaterLine: false,
        hasGasLine: false,
    },
    bathrooms: 0,
    bedrooms: 0,
    kitchenType: 0,
    floors: 0,
    images: [],
};
export const defaultCommercialValues: ListingFormInputs = {
    propertyPurpose: 0,
    title: "",
    agentId: "",
    propertyStatus: 0,
    propertyType: 1,
    compoundId: "",
    address: "",
    city: "",
    googleMapsUrl: "",
    price: 0,
    square: 0,
    description: "",
    amenities: {
        hasElectricityLine: false,
        hasWaterLine: false,
        hasGasLine: false,
    },
    floorNumber: 0,
    businessType: "",
    hasStorage: false,
    images: [],
};
